services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-0
    restart: always
    command: ["mongod", "--config", "/etc/mongod.conf"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
      - MONGO_APP_USER_PASSWORD=${MONGO_APP_USER_PASSWORD}
      - MONGO_READONLY_USER_PASSWORD=${MONGO_READONLY_USER_PASSWORD}
      - MONGO_DATABASE_NAME=db0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongod.conf:/etc/mongod.conf:ro
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "'db.adminCommand(\"ping\").ok'", "--quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - mongodb-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16GB

volumes:
  mongodb_data:
    external: true
    # Switch to local if you don't want to create a volume using docker volume create
    # driver: local

networks:
  mongodb-network:
    driver: bridge
